---
version: '2'
services:
  web:
    container_name: golang
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      RESTAPIPROJECT_DBHOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - appnet

  mysql:
    image: mysql
    container_name: db
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: g7y48UPH
      MYSQL_DATABASE: restApi
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 2s
      retries: 20
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
