---
version: '3'
services:
  web:
    container_name: golang
    build:
      context: .
      dockerfile: ./Dockerfile.web
    ports:
      - "8080:8080"
    env_file:
      - cmd/rest_api/.env
    environment:
      REST_API_DBHOST: mysql
      REST_API_GRPCHOST: grpc
    depends_on:
      - mysql
      - grpc
    restart: on-failure
    networks:
      - appnet

  grpc:
    container_name: golang_grpc
    build:
      context: .
      dockerfile: ./Dockerfile.grpc
    ports:
      - "9000:9000"
    env_file:
      - cmd/grpc/.env
    networks:
      - appnet

  mysql:
    image: mysql
    container_name: db
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: g7y48UPH!
      MYSQL_DATABASE: restApi
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
