/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [
    "intro",
    {
      type: "category",
      label: "Answers",
      link: {
        type: "generated-index",
        description: "Ответы на вопросы.",
//         slug: "answers",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "answers",
        },
      ],
    },
    {
      type: "category",
      label: "API reference",
      link: {
        type: "generated-index",
        title: "API reference",
        description:
          "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "api-reference"
      },
      items: [
        {
          type: "category",
          label: "Payments",
          link: {
            type: "doc",
            id: "api-reference/payments",
          },
          items: [
            {
              type: "doc",
              id: "api-reference/payments/create-payment",
              label: "Создание рублёвого платёжного поручения",
              className: "api-method post",
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;