openapi: 3.0.2
info:
  title: Payments Overview
  version: 1.0.0

servers:
  - url: https://fintech.sberbank.ru:9443/fintech/api
  - url: https://iftfintech.testsbi.sberbank.ru:9443/fintech/api

tags:
  - name: payments
    description: Everything about your Pets
    x-displayName: Payments

paths:
  /v1/payments:
    post:
      tags:
        - payments
      summary: Создание рублёвого платёжного поручения
      description:
      operationId: createPayment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/FintechPaymentIncoming'
        required: true
      responses:
        201:
          description: Успешный запрос
          content:
            application/json:
              schema:
                ApiResponse:
                  type: object
                  properties:
                    code:
                      type: integer
                      format: int32
                    type:
                      type: string
                    message:
                      type: string
                $ref: '#/components/schemas/FintechPayment'
        202:
          description: Операция не завершена полностью
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FintechWorkflowFault'
        "418":
          description: |
            I'm a teapot

            The requested entity body is short and stout.
    patch:
      tags:
        - payments
      summary: Обновление рублёвого платёжного поручения
      description:
      operationId: patchPayment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/FintechPaymentIncoming'
        required: true
      responses:
        201:
          description: Успешный запрос
          content:
            application/json:
              schema:
                ApiResponse:
                  type: object
                  properties:
                    code:
                      type: integer
                      format: int32
                    type:
                      type: string
                    message:
                      type: string
                $ref: '#/components/schemas/FintechPayment'
        202:
          description: Операция не завершена полностью
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FintechWorkflowFault'
        "418":
          description: |
            I'm a teapot

            The requested entity body is short and stout.
components:
  requestBodies:
    FintechPaymentIncoming:
      type: object
      required:
        - date
        - externalId
        - amount
        - operationCode
        - priority
        - purpose
        - payerName
        - payerInn
        - payerAccount
        - payerBankBic
        - payerBankCorrAccount
        - payeeName
        - payeeBankBic
      properties:
        number:
          type: string
          description: Номер документа
        date:
          type: string
          format: date
          description: Дата составления документа
        digestSignatures:
          type: array
          description: Электронные подписи по дайджесту документа
          items:
            type: object
            required:
              - certificateUuid
              - base64Encoded
            properties:
              certificateUuid:
                type: string
                format: uuid
                description: Уникальный идентификатор сертификата ключа проверки электронной подписи (UUID)
              base64Encoded:
                type: string
                enum: ["non-empty"]
                description: Значение электронной подписи, закодированное в Base64
        bankStatus:
          type: string
          description: Статус документа
        bankComment:
          type: string
          description: Банковский комментарий к статусу документа
        externalId:
          type: string
          format: uuid
          description: Идентификатор документа, присвоенный партнером (UUID)
        amount:
          type: number
          default: 0
          description: Сумма платежа
        operationCode:
          type: string
          pattern: "^01$"
          description: Код операции
        deliveryKind:
          type: string
          pattern: "^(электронно|срочно|0)"
          description: Способ доставки документа
        priority:
          type: string
          pattern: "^[1-5]{1}$"
          description: Очередность платежа
        urgencyCode:
          type: string
          enum: [INTERNAL, INTERNAL_NOTIF, OFFHOURS, BESP, NORMAL]
          description: |
            Код срочности

            Возможные значения:
            - INTERNAL – срочный
            - INTERNAL_NOTIF – срочный платеж с уведомлением
            - OFFHOURS – неотложный
            - BESP – банковские электронные срочные платежи
            - NORMAL – срочность не указана
        voCode:
          type: string
          pattern: "^[0-9]{5}$"
          description: Код вида валютной операции
        purpose:
          type: string
          maxLength: 210
          description: |
            Назначение платежа

            Допустимые символы:
            - цифры (0–9), латиница (a–z, A–Z) и кириллица (а–я, А–Я, Ёё)
            - спецсимволы: ! " # $ % & ' ( ) [ ] * . , : ; - / \ < = > ? @ ^ _ ` { | } ~ №
            - пробел, перенос строки (\n), возврат каретки (\r)
        departmentalInfo:
          type: object
          description: Реквизиты налогового, таможенного или иного бюджетного платежа
          properties:
            uip:
              type: string
              maxLength: 25
              pattern: "^[A-ZА-Я0-9/]+$"
              description: Уникальный идентификатор платежа
            drawerStatus101:
              type: string
              maxLength: 2
              description: Показатель статуса налогоплательщика (реквизит – 101)
            kbk:
              type: string
              pattern: "^([A-ZА-Я0-9]{1,20})$"
              description: Код бюджетной классификации (реквизит – 104)
            oktmo:
              type: string
              pattern: "^.{1,8}$"
              description: Код OKTMO (реквизит – 105)
            reasonCode106:
              type: string
              maxLength: 2
              description: Показатель основания платежа (реквизит – 106)
            taxPeriod107:
              type: string
              pattern: "^(0|[0-9]{8}|([0-9]{2}|МС|КВ|ПЛ|ГД)\\.[0-9]{2}\\.[0-9]{4})$"
              description: Налоговый период / код таможенного органа (реквизит – 107)
            docNumber108:
              type: string
              maxLength: 15
              description: Номер налогового документа (реквизит – 108)
            docDate109:
              type: string
              pattern: "^(0|00|[0-9]{2}\\.[0-9]{2}\\.[0-9]{4})$"
              description: Дата налогового документа (реквизит – 109)
            paymentKind110:
              type: string
              maxLength: 2
              description: Тип налогового платежа (реквизит – 110)
        payerName:
          type: string
          maxLength: 254
          description: Полное наименование плательщика
        payerInn:
          type: string
          pattern: "^([0-9]{5}|[0-9]{10}|[0-9]{12}|0)$"
          description: ИНН плательщика
        payerKpp:
          type: string
          pattern: "^([0-9]{9}|0)$"
          description: КПП плательщика
        payerAccount:
          type: string
          pattern: "^[0-9]{20}$"
          description: Счет плательщика
        payerBankBic:
          type: string
          pattern: "^[0-9]{9}$"
          description: БИК банка плательщика
        payerBankCorrAccount:
          type: string
          pattern: "^[0-9]{20}$"
          description: Корсчет банка плательщика
        payeeName:
          type: string
          maxLength: 254
          description: Полное наименование получателя платежа
        payeeInn:
          type: string
          pattern: "^([0-9]{5}|[0-9]{10}|[0-9]{12}|0)$"
          description: ИНН получателя платежа
        payeeKpp:
          type: string
          pattern: "^([0-9]{9}|0)$"
          description: КПП получателя платежа
        payeeAccount:
          type: string
          pattern: "^[0-9]{20}$"
          description: Счет получателя платежа
        payeeBankBic:
          type: string
          pattern: "^[0-9]{9}$"
          description: БИК получателя платежа
        payeeBankCorrAccount:
          type: string
          pattern: "^[0-9]{20}$"
          description: Корсчет банка получателя платежа
        crucialFieldsHash:
          type: string
          description: Hash от ключевых полей документа
        vat:
          type: object
          nullable: true
          required:
            - type
          description: Данные НДС
          properties:
            type:
              type: string
              nullable: true
              enum: [INCLUDED, ONTOP, NO_VAT, MANUAL]
              description: |
                Способ расчета НДС

                Возможные значения:
                - INCLUDED – НДС включен в сумму платежа
                - ONTOP – НДС рассчитан по указанной ставке и добавляется к сумме платежа
                - NO_VAT – не облагается НДС
                - MANUAL – ручной ввод НДС
            rate:
              type: string
              nullable: true
              pattern: "^(0|5|7|10|20)$"
              description: Ставка НДС
            amount:
              type: number
              nullable: true
              description: Сумма НДС
        incomeTypeCode:
          type: string
          maxLength: 2
          description: Код вида дохода получателей выплаты по 229-ФЗ
        isPaidByCredit:
          type: boolean
          description: Признак того, что платежное поручение будет оплачено за счет кредитных средств
        creditContractNumber:
          type: string
          maxLength: 50
          description: Номер кредитного договора

  schemas:
    FintechPayment:
      type: object
      required:
        - date
        - externalId
        - amount
        - operationCode
        - priority
        - purpose
        - payerName
        - payerInn
        - payerAccount
        - payerBankBic
        - payerBankCorrAccount
        - payeeName
        - payeeBankBic
      properties:
        number:
          type: string
          description: Номер документа
        date:
          type: string
          format: date
          description: Дата составления документа
        digestSignatures:
          type: array
          description: Электронные подписи по дайджесту документа
          items:
            type: object
            required:
              - certificateUuid
              - base64Encoded
            properties:
              certificateUuid:
                type: string
                format: uuid
                description: Уникальный идентификатор сертификата ключа проверки электронной подписи (UUID)
              base64Encoded:
                type: string
                enum: [ "non-empty" ]
                description: Значение электронной подписи, закодированное в Base64
        bankStatus:
          type: string
          description: Статус документа
        bankComment:
          type: string
          description: Банковский комментарий к статусу документа
        externalId:
          type: string
          format: uuid
          description: Идентификатор документа, присвоенный партнером (UUID)
        amount:
          type: number
          default: 0
          description: Сумма платежа
        operationCode:
          type: string
          pattern: "^01$"
          description: Код операции
        deliveryKind:
          type: string
          pattern: "^(электронно|срочно|0)"
          description: Идентификатор документа, присвоенный партнером (UUID)
        priority:
          type: string
          pattern: "^[1-5]{1}$"
          description: Очередность платежа
        urgencyCode:
          type: string
          enum: [ INTERNAL, INTERNAL_NOTIF, OFFHOURS, BESP, NORMAL ]
          description: |
            Код срочности
    
            Возможные значения:
            - INTERNAL – срочный
            - INTERNAL_NOTIF – срочный платеж с уведомлением
            - OFFHOURS – неотложный
            - BESP – банковские электронные срочные платежи
            - NORMAL – срочность не указана
        voCode:
          type: string
          pattern: "^[0-9]{5}$"
          description: Код вида валютной операции
        purpose:
          type: string
          maxLength: 210
          description: |
            Назначение платежа
    
            Допустимые символы:
            - цифры (0–9), латиница (a–z, A–Z) и кириллица (а–я, А–Я, Ёё)
            - спецсимволы: ! " # $ % & ' ( ) [ ] * . , : ; - / \ < = > ? @ ^ _ ` { | } ~ №
            - пробел, перенос строки (\n), возврат каретки (\r)
        departmentalInfo:
          type: object
          description: Реквизиты налогового, таможенного или иного бюджетного платежа
          properties:
            uip:
              type: string
              maxLength: 25
              pattern: "^[A-ZА-Я0-9/]+$"
              description: Уникальный идентификатор платежа
            drawerStatus101:
              type: string
              maxLength: 2
              description: Показатель статуса налогоплательщика (реквизит – 101)
            kbk:
              type: string
              pattern: "^([A-ZА-Я0-9]{1,20})$"
              description: Код бюджетной классификации (реквизит – 104)
            oktmo:
              type: string
              pattern: "^.{1,8}$"
              description: Код OKTMO (реквизит – 105)
            reasonCode106:
              type: string
              maxLength: 2
              description: Показатель основания платежа (реквизит – 106)
            taxPeriod107:
              type: string
              pattern: "^(0|[0-9]{8}|([0-9]{2}|МС|КВ|ПЛ|ГД)\\.[0-9]{2}\\.[0-9]{4})$"
              description: Налоговый период / код таможенного органа (реквизит – 107)
            docNumber108:
              type: string
              maxLength: 15
              description: Номер налогового документа (реквизит – 108)
            docDate109:
              type: string
              pattern: "^(0|00|[0-9]{2}\\.[0-9]{2}\\.[0-9]{4})$"
              description: Дата налогового документа (реквизит – 109)
            paymentKind110:
              type: string
              maxLength: 2
              description: Тип налогового платежа (реквизит – 110)
        payerName:
          type: string
          maxLength: 254
          description: Полное наименование плательщика
        payerInn:
          type: string
          pattern: "^([0-9]{5}|[0-9]{10}|[0-9]{12}|0)$"
          description: ИНН плательщика
        payerKpp:
          type: string
          pattern: "^([0-9]{9}|0)$"
          description: КПП плательщика
        payerAccount:
          type: string
          pattern: "^[0-9]{20}$"
          description: Счет плательщика
        payerBankBic:
          type: string
          pattern: "^[0-9]{9}$"
          description: БИК банка плательщика
        payerBankCorrAccount:
          type: string
          pattern: "^[0-9]{20}$"
          description: Корсчет банка плательщика
        payeeName:
          type: string
          maxLength: 254
          description: Полное наименование получателя платежа
        payeeInn:
          type: string
          pattern: "^([0-9]{5}|[0-9]{10}|[0-9]{12}|0)$"
          description: ИНН получателя платежа
        payeeKpp:
          type: string
          pattern: "^([0-9]{9}|0)$"
          description: КПП получателя платежа
        payeeAccount:
          type: string
          pattern: "^[0-9]{20}$"
          description: Счет получателя платежа
        payeeBankBic:
          type: string
          pattern: "^[0-9]{9}$"
          description: БИК получателя платежа
        payeeBankCorrAccount:
          type: string
          pattern: "^[0-9]{20}$"
          description: Корсчет банка получателя платежа
        crucialFieldsHash:
          type: string
          description: Hash от ключевых полей документа
        vat:
          type: object
          nullable: true
          required:
            - type
          description: Данные НДС
          properties:
            type:
              type: string
              nullable: true
              enum: [ INCLUDED, ONTOP, NO_VAT, MANUAL ]
              description: |
                Способ расчета НДС
    
                Возможные значения:
                - INCLUDED – НДС включен в сумму платежа
                - ONTOP – НДС рассчитан по указанной ставке и добавляется к сумме платежа
                - NO_VAT – не облагается НДС
                - MANUAL – ручной ввод НДС
            rate:
              type: string
              nullable: true
              pattern: "^(0|5|7|10|20)$"
              description: Ставка НДС
            amount:
              type: number
              nullable: true
              description: Сумма НДС
        incomeTypeCode:
          type: string
          maxLength: 2
          description: Код вида дохода получателей выплаты по 229-ФЗ
    FintechWorkflowFault:
      type: object
      properties:
        checks:
          type: array
          description: Список проверок, приведших к ошибке
          items:
            type: object
            properties:
              level:
                type: string
                description: Уровень результата
              message:
                type: string
                description: Сообщение
              fields:
                type: array
                items:
                  type: string
                description: Названия полей (при наличии связи с моделью)
        cause:
          type: string
          description: Причина или основание сообщения
        message:
          type: string
          description: Сообщение
        referenceId:
          type: string
          format: uuid
          description: Уникальный идентификатор ошибки (UUID)
        internalErrorCode:
          type: string
          description: |
            Внутренний код ошибки.

            Указывайте его при обращении в поддержку вместе с ответом по возникшей ошибке.